- src/main/java/com/devathon/slytherin/config/SwaggerConfig.java
update Swagger configuration with production server URL
> docs(swagger): update Swagger configuration with production server URL

- .github/workflows/deploy.yml
add GitHub Actions workflow for deployment to server
> ci(workflow): add GitHub Actions workflow for deployment to server

- src/main/java/com/devathon/slytherin/DTOs/CategoryDto.java
- src/main/java/com/devathon/slytherin/DTOs/CategoryResponseDto.java
- src/main/java/com/devathon/slytherin/DTOs/MagicObjectResponseDto.java
- src/main/java/com/devathon/slytherin/DTOs/RarityDto.java
- src/main/java/com/devathon/slytherin/DTOs/RarityResponseDto.java
- src/main/java/com/devathon/slytherin/controllers/CategoryController.java
- src/main/java/com/devathon/slytherin/controllers/MagicObjectController.java
- src/main/java/com/devathon/slytherin/controllers/RarityController.java
- src/main/java/com/devathon/slytherin/mappers/CategoryMapper.java
- src/main/java/com/devathon/slytherin/mappers/RarityMapper.java
- src/main/java/com/devathon/slytherin/models/CategoryModel.java
- src/main/java/com/devathon/slytherin/models/MagicObjectModel.java
- src/main/java/com/devathon/slytherin/models/RarityModel.java
- src/main/java/com/devathon/slytherin/repositories/CategoryRepository.java
- src/main/java/com/devathon/slytherin/repositories/RarityRepository.java
- src/main/java/com/devathon/slytherin/services/CategoryService.java
- src/main/java/com/devathon/slytherin/services/MagicObjectService.java
- src/main/java/com/devathon/slytherin/services/RarityService.java
add Rarity and Category models, repositories, mappers, and services with DTOs for handling magic objects
> feat: modify magic objects service

- src/main/java/com/devathon/slytherin/config/DataSeeder.java
update magic object descriptions to short_description in DataSeeder
> fix: update DataSeeder

- src/main/java/com/devathon/slytherin/config/DataSeeder.java
extend DataSeeder to include category and rarity creation for magic objects
> feat: extend DataSeeder

- src/main/java/com/devathon/slytherin/DTOs/MagicObjectPaginatorResponseDto.java
- src/main/java/com/devathon/slytherin/controllers/MagicObjectController.java
- src/main/java/com/devathon/slytherin/mappers/MagicObjectMapper.java
- src/main/java/com/devathon/slytherin/services/MagicObjectService.java
> fix : update for get all with paginator

- src/main/resources/application.properties
Add base path configuration for the API in application.properties
> feat: Add base path configuration for the API in application.properties

- src/main/java/com/devathon/slytherin/DTOs/WishlistDto.java
- src/main/java/com/devathon/slytherin/DTOs/WishlistGroupedResponseDto.java
- src/main/java/com/devathon/slytherin/controllers/WishlistController.java
- src/main/java/com/devathon/slytherin/models/WishlistModel.java
- src/main/java/com/devathon/slytherin/repositories/WishlistRepository.java
- src/main/java/com/devathon/slytherin/services/WishlistService.java
Implement DTOs and services for managing user wish lists
> feat: Implement DTOs and services for managing user wish lists

- src/main/java/com/devathon/slytherin/DTOs/CurrencyDto.java
- src/main/java/com/devathon/slytherin/DTOs/SaleDto.java
- src/main/java/com/devathon/slytherin/DTOs/SaleItemDto.java
- src/main/java/com/devathon/slytherin/DTOs/SaleItemRequestDto.java
- src/main/java/com/devathon/slytherin/DTOs/SaleItemResponseDto.java
- src/main/java/com/devathon/slytherin/DTOs/SaleRequestDto.java
- src/main/java/com/devathon/slytherin/controllers/SaleController.java
- src/main/java/com/devathon/slytherin/mappers/SaleItemMapper.java
- src/main/java/com/devathon/slytherin/mappers/SaleMapper.java
- src/main/java/com/devathon/slytherin/models/SaleItemModel.java
- src/main/java/com/devathon/slytherin/models/SaleModel.java
- src/main/java/com/devathon/slytherin/repositories/SaleItemRepository.java
- src/main/java/com/devathon/slytherin/repositories/SaleRepository.java
- src/main/java/com/devathon/slytherin/services/CurrencyService.java
- src/main/java/com/devathon/slytherin/services/SaleItemService.java
- src/main/java/com/devathon/slytherin/services/SaleService.java
- src/main/java/com/devathon/slytherin/services/UserService.java
Implement sale and currency management with DTOs, services, and repositories
> feat: Implement sale and currency management

- src/main/java/com/devathon/slytherin/DTOs/PurchaseHistoryDto.java
- src/main/java/com/devathon/slytherin/controllers/SaleController.java
- src/main/java/com/devathon/slytherin/repositories/SaleRepository.java
- src/main/java/com/devathon/slytherin/services/SaleService.java
Endpoint que muestra el historial de compras
- Endpoint que a partir del id usuario retorna el historial de compras con datos de la fecha, precio y objeto
- La lista que devuelve está ordenada por fecha más reciente de la venta a más antigua
> Endpoint que muestra el historial de compras

- src/main/java/com/devathon/slytherin/controllers/MagicObjectController.java
- src/main/java/com/devathon/slytherin/repositories/MagicObjectRepository.java
- src/main/java/com/devathon/slytherin/services/MagicObjectService.java
feat: Returns a paginated list of magic items filtered by category ID.
> feat: Returns a paginated list of magic items filtered by category ID.

- src/main/java/com/devathon/slytherin/DTOs/UserDto.java
- src/main/java/com/devathon/slytherin/DTOs/UserResponseDto.java
- src/main/java/com/devathon/slytherin/config/DataSeeder.java
- src/main/java/com/devathon/slytherin/controllers/UserController.java
- src/main/java/com/devathon/slytherin/models/UserModel.java
- src/main/java/com/devathon/slytherin/services/UserService.java
Comment out house-related fields and logic in DTOs and services
> refactor: Comment out house-related fields

- src/main/java/com/devathon/slytherin/config/DataSeeder.java
Remove houseModel references from sales in DataSeeder
> refactor: Remove houseModel references from sales in DataSeeder

- src/main/java/com/devathon/slytherin/controllers/HouseController.java
- src/main/java/com/devathon/slytherin/controllers/MagicObjectController.java
- src/main/java/com/devathon/slytherin/repositories/MagicObjectRepository.java
- src/main/java/com/devathon/slytherin/services/MagicObjectService.java
Unify service to filter unsold magic objects by category
> refactor: Unify service of magic objects

- src/main/java/com/devathon/slytherin/DTOs/WishlistGroupedResponseDto.java
- src/main/java/com/devathon/slytherin/DTOs/WishlistObjectsResponseDto.java
- src/main/java/com/devathon/slytherin/controllers/WishlistController.java
- src/main/java/com/devathon/slytherin/services/WishlistService.java
Update wishlist DTOs to use WishlistObjectsResponseDto and improve operation descriptions
> refactor: Update wishlist DTOs to use WishlistObjectsResponseDto

- src/main/java/com/devathon/slytherin/controllers/SaleController.java
- src/main/java/com/devathon/slytherin/services/SaleService.java
- src/main/java/com/devathon/slytherin/services/UserService.java
fix update balance method and sale history issues
> fix update balance method and sale history issues

- src/main/java/com/devathon/slytherin/DTOs/SaleDto.java
- src/main/java/com/devathon/slytherin/DTOs/SaleRequestDto.java
- src/main/java/com/devathon/slytherin/DTOs/UserResponseDto.java
- src/main/java/com/devathon/slytherin/DTOs/WishlistDto.java
- src/main/java/com/devathon/slytherin/config/DataSeeder.java
- src/main/java/com/devathon/slytherin/controllers/SaleController.java
- src/main/java/com/devathon/slytherin/controllers/UserController.java
- src/main/java/com/devathon/slytherin/controllers/WishlistController.java
- src/main/java/com/devathon/slytherin/models/UserModel.java
- src/main/java/com/devathon/slytherin/repositories/UserRepository.java
- src/main/java/com/devathon/slytherin/services/SaleService.java
- src/main/java/com/devathon/slytherin/services/UserService.java
- src/main/java/com/devathon/slytherin/services/WishlistService.java
Change user_id and id fields from Long to String in DTOs, models, and services for consistency
> refactor: Change user_id 

- src/main/java/com/devathon/slytherin/DTOs/UserResponseDto.java
- src/main/java/com/devathon/slytherin/config/DataSeeder.java
- src/main/java/com/devathon/slytherin/models/UserModel.java
- src/main/java/com/devathon/slytherin/services/UserService.java
Add field image_url to usuer adjust DataSeeder.java
> feat: agrega campo image_url a usuario y ajusta DataSeeder

- src/main/java/com/devathon/slytherin/controllers/MagicObjectController.java
- src/main/java/com/devathon/slytherin/repositories/MagicObjectRepository.java
- src/main/java/com/devathon/slytherin/services/MagicObjectService.java
Add endpoint to retrieve unsold magic objects filtered by rarity
> feat: Add endpoint to retrieve unsold magic objects filtered by rarity

- src/main/java/com/devathon/slytherin/config/DataSeeder.java
Add mythical objects to the magic object repository with detailed descriptions and categories
> feat: Add mythical objects to the magic object repository

- src/main/java/com/devathon/slytherin/repositories/MagicObjectRepository.java
- src/main/java/com/devathon/slytherin/services/MagicObjectService.java
Enhance MagicObjectRepository and MagicObjectService with new filtering methods to exclude specific rarity
> feat: Enhance MagicObjectRepository and MagicObjectService with new filtering methods
